### ISSUE TITLE
Can't add data with addBrandSurftech.js

### ISSUE THREAD

**Issue by tripott** [mtheodo/api-examv1.0#2]
`node addBrandSurftech.js` causes the following errors:

/Users/wottinger/Dropbox/JRS/code/tests/api-exam/matt/addBrandSurftech.js:31
    dalNoSQL.createSurftech(board, callback('Surftech Board CREATED:\n'))
             ^

TypeError: dalNoSQL.createSurftech is not a function
    at /Users/wottinger/Dropbox/JRS/code/tests/api-exam/matt/addBrandSurftech.js:31:14

**Comment by mtheodo** [comment]
finally got this one fixed
